package grogshop;

import com.grogdj.grogshop.core.model.*;
import org.grogshop.services.api.*;
import org.grogshop.services.impl.*;

global NotificationsService notificationsService;
global MatchingsService matchingsService;


rule "matching membership and listing"
  when
    // When I have a list that matches with all the bidders 
    $l: Listing($listingTags: tags, $listingPriceRange: priceRange)
    $m: ClubMembership(tags matchp $listingTags)
  then
    notificationsService.notifyUser($l.getUserId(), "Matching: club member interested in the listing", "user");
    notificationsService.notifyUser($m.getUserId(), "Matching: new listing in club ", "user");
    Matching newMatching = new Matching($l, $m, "Full Match");
    matchingsService.newMatching(newMatching);
    insertLogical(newMatching);
    notificationsService.notifyMatching($l.getUserId(), $m.getUserId(),  newMatching);
end


