package grogshop;

import com.grogdj.grogshop.core.model.*;
import org.grogshop.services.api.*;
import org.grogshop.services.impl.*;

global NotificationsService notificationsService;
global MatchingsService matchingsService;


rule "item matching request"
  when

    $p: Item(type == Item.ItemType.POST, $club: club, $postTags: tags, $postPrice: minPrice )
    $r: Item(type == Item.ItemType.REQUEST, tags matchp $postTags, minPrice < $postPrice, maxPrice > $postPrice)
  then
    
    Matching newMatching = new Matching($club, $p, $r);
    matchingsService.newMatching(newMatching);
    insertLogical(newMatching);
    System.out.println("New Matching for:  item(post): "+ $p + " itemMatched (request): "+$r);
end


